ether_type.0x05DC=802.3
ether_type.0x0800=IPv4
ether_type.0x0806=ARP
ether_type.0x0842=WoL
ether_type.0x22ea=SRP
ether_type.0x22f0=AVTP
ether_type.0x22f3=TRILL
ether_type.0x6002=DEC MOP RC
ether_type.0x6003=DECnet
ether_type.0x6004=DEC LAT
ether_type.0x8035=RARP
ether_type.0x809b=AppleTalk
ether_type.0x80d5=LLC PDU
ether_type.0x80f3=AARP
ether_type.0x8100=802.1Q
ether_type.0x8102=SLPP
ether_type.0x8103=VLACP
ether_type.0x8137=IPX
ether_type.0x8204=Qnet
ether_type.0x86dd=IPv6
ether_type.0x8808=Flow Control
ether_type.0x8809=Slow Protocols
ether_type.0x8819=CobraNet
ether_type.0x8847=MPLS Unicast
ether_type.0x8848=MPLS Multicast
ether_type.0x8863=PPPoE Discovery
ether_type.0x8864=PPPoE Session
ether_type.0x887b=HomePlug 1.0
ether_type.0x888e=802.1X
ether_type.0x8892=PROFINET
ether_type.0x889a=HyperSCSI
ether_type.0x88a2=AoE
ether_type.0x88a4=EtherCAT
ether_type.0x88a8=802.1ad
ether_type.0x88ab=EPL
ether_type.0x88b8=GOOSE
ether_type.0x88b9=GSE
ether_type.0x88ba=SV
ether_type.0x88bf=RoMON
ether_type.0x88cc=LLDP
ether_type.0x88cd=SERCOS III
ether_type.0x88e1=HomePlug GP
ether_type.0x88e3=MRP
ether_type.0x88e5=MACsec
ether_type.0x88e7=PBB
ether_type.0x88f7=PTP
ether_type.0x88f8=NC-SI
ether_type.0x88fb=PRP
ether_type.0x8902=CFM
ether_type.0x8906=FCoE
ether_type.0x8914=FIP
ether_type.0x8915=RoCE
ether_type.0x891d=TTE
ether_type.0x893a=1905.1
ether_type.0x892f=HSR
ether_type.0x9000=Config Test
ether_type.0xf1c1=802.1CB
ether_type.0x8874=Broadcom Mgmt