ether_type.0x05DC=IEEE 802.3
ether_type.0x0800=Internet Protocol version 4 (IPv4)
ether_type.0x0806=Address Resolution Protocol (ARP)
ether_type.0x0842=Wake-on-LAN
ether_type.0x22ea=Stream Reservation Protocol
ether_type.0x22f0=Audio Video Transport Protocol (AVTP)
ether_type.0x22f3=IETF TRILL Protocol
ether_type.0x6002=DEC MOP RC
ether_type.0x6003=DECnet Phase IV, DNA Routing
ether_type.0x6004=DEC LAT
ether_type.0x8035=Reverse Address Resolution Protocol (RARP)
ether_type.0x809b=AppleTalk (EtherTalk)
ether_type.0x80d5=LLC PDU (in particular, IBM SNA), preceded by 2 bytes length and 1 byte padding
ether_type.0x80f3=AppleTalk Address Resolution Protocol (AARP)
ether_type.0x8100=VLAN-tagged frame (IEEE 802.1Q) and Shortest Path Bridging IEEE 802.1aq with NNI compatibility
ether_type.0x8102=Simple Loop Prevention Protocol (SLPP)
ether_type.0x8103=Virtual Link Aggregation Control Protocol (VLACP)
ether_type.0x8137=IPX
ether_type.0x8204=QNX Qnet
ether_type.0x86dd=Internet Protocol Version 6 (IPv6)
ether_type.0x8808=Ethernet flow control
ether_type.0x8809=Ethernet Slow Protocols such as the Link Aggregation Control Protocol (LACP)
ether_type.0x8819=CobraNet
ether_type.0x8847=MPLS unicast
ether_type.0x8848=MPLS multicast
ether_type.0x8863=PPPoE Discovery Stage
ether_type.0x8864=PPPoE Session Stage
ether_type.0x887b=HomePlug 1.0 MME
ether_type.0x888e=EAP over LAN (IEEE 802.1X)
ether_type.0x8892=PROFINET Protocol
ether_type.0x889a=HyperSCSI (SCSI over Ethernet)
ether_type.0x88a2=ATA over Ethernet
ether_type.0x88a4=EtherCAT Protocol
ether_type.0x88a8=Service VLAN tag identifier (S-Tag) on Q-in-Q tunnel
ether_type.0x88ab=Ethernet Powerlink
ether_type.0x88b8=GOOSE (Generic Object Oriented Substation event)
ether_type.0x88b9=GSE (Generic Substation Events) Management Services
ether_type.0x88ba=SV (Sampled Value Transmission)
ether_type.0x88bf=MikroTik RoMON (unofficial)
ether_type.0x88cc=Link Layer Discovery Protocol (LLDP)
ether_type.0x88cd=SERCOS III
ether_type.0x88e1=HomePlug Green PHY
ether_type.0x88e3=Media Redundancy Protocol (IEC62439-2)
ether_type.0x88e5=IEEE 802.1AE MAC security (MACsec)
ether_type.0x88e7=Provider Backbone Bridges (PBB) (IEEE 802.1ah)
ether_type.0x88f7=Precision Time Protocol (PTP) over IEEE 802.3 Ethernet
ether_type.0x88f8=NC-SI
ether_type.0x88fb=Parallel Redundancy Protocol (PRP)
ether_type.0x8902=IEEE 802.1ag Connectivity Fault Management (CFM) Protocol / ITU-T Recommendation Y.1731 (OAM)
ether_type.0x8906=Fibre Channel over Ethernet (FCoE)
ether_type.0x8914=FCoE Initialization Protocol
ether_type.0x8915=RDMA over Converged Ethernet (RoCE)
ether_type.0x891d=TTEthernet Protocol Control Frame (TTE)
ether_type.0x893a=1905.1 IEEE Protocol
ether_type.0x892f=High-availability Seamless Redundancy (HSR)
ether_type.0x9000=Ethernet Configuration Testing Protocol
ether_type.0xf1c1=Redundancy Tag (IEEE 802.1CB Frame Replication and Elimination for Reliability)
ether_type.0x8874=Broadcom Ethernet Management