tcp_port.7=Echo
tcp_port.9=Discard
tcp_port.11=Systat
tcp_port.13=Daytime
tcp_port.17=QOTD
tcp_port.19=Chargen
tcp_port.20=FTP-DATA
tcp_port.21=FTP
tcp_port.22=SSH
tcp_port.23=Telnet
tcp_port.25=SMTP
tcp_port.37=Time
tcp_port.42=Nameserver
tcp_port.43=WHOIS
tcp_port.49=TACACS
tcp_port.53=DNS
tcp_port.67=DHCP-Server
tcp_port.68=DHCP-Client
tcp_port.69=TFTP
tcp_port.70=Gopher
tcp_port.79=Finger
tcp_port.80=HTTP
tcp_port.88=Kerberos
tcp_port.102=ISO-TSAP
tcp_port.104=DICOM
tcp_port.105=CCSO
tcp_port.107=Rtelnet
tcp_port.109=POP2
tcp_port.110=POP3
tcp_port.111=RPC
tcp_port.113=Auth
tcp_port.115=SFTP
tcp_port.117=UUCP
tcp_port.119=NNTP
tcp_port.123=NTP
tcp_port.135=EPMAP
tcp_port.137=NetBIOS-NS
tcp_port.138=NetBIOS-DGM
tcp_port.139=NetBIOS-SSN
tcp_port.143=IMAP
tcp_port.161=SNMP
tcp_port.162=SNMP-Trap
tcp_port.163=CMIP-Man
tcp_port.164=CMIP-Agent
tcp_port.174=MAILQ
tcp_port.177=XDMCP
tcp_port.178=NeXTStep
tcp_port.179=BGP
tcp_port.191=Prospero
tcp_port.194=IRC
tcp_port.199=SMUX
tcp_port.201=AT-RTMP
tcp_port.202=AT-NBP
tcp_port.204=AT-Echo
tcp_port.206=AT-ZIS
tcp_port.209=QMTP
tcp_port.210=Z39.50
tcp_port.213=IPX
tcp_port.220=IMAP3
tcp_port.259=ESRO
tcp_port.264=BGMP
tcp_port.280=HTTP-Mgmt
tcp_port.308=Novastor
tcp_port.311=Mac-Admin
tcp_port.318=PKIX-TSP
tcp_port.319=PTP-Event
tcp_port.320=PTP-General
tcp_port.350=MATIP-A
tcp_port.351=MATIP-B
tcp_port.366=ODMR
tcp_port.369=Rpc2portmap
tcp_port.370=Codaauth2
tcp_port.371=ClearCase
tcp_port.383=HP-Alarm
tcp_port.384=ARNS
tcp_port.387=AURP
tcp_port.389=LDAP
tcp_port.399=DECnet+
tcp_port.401=UPS
tcp_port.427=SLP
tcp_port.443=HTTPS
tcp_port.444=SNPP
tcp_port.445=SMB
tcp_port.464=Kpasswd
tcp_port.465=SMTPS
tcp_port.475=tcpnethaspsrv
tcp_port.497=Retrospect
tcp_port.500=ISAKMP
tcp_port.502=Modbus
tcp_port.504=Citadel
tcp_port.510=FirstClass
tcp_port.512=Rexec
tcp_port.513=Rlogin
tcp_port.514=Rsh
tcp_port.515=LPD
tcp_port.517=Talk
tcp_port.518=NTalk
tcp_port.520=RIP
tcp_port.521=RIPng
tcp_port.524=NCP
tcp_port.525=Timed
tcp_port.530=RPC
tcp_port.532=netnews
tcp_port.533=netwall
tcp_port.540=UUCP
tcp_port.542=Commerce
tcp_port.543=Klogin
tcp_port.544=RTSP
tcp_port.546=DHCPv6-Client
tcp_port.547=DHCPv6-Server
tcp_port.548=AFP
tcp_port.550=new-who
tcp_port.554=RTSP
tcp_port.556=Remotefs
tcp_port.560=rmonitor
tcp_port.561=monitor
tcp_port.563=NNTPS
tcp_port.564=9pfs
tcp_port.585=IMAPS-Legacy
tcp_port.587=Submission
tcp_port.591=FileMaker
tcp_port.593=MS-DCOM
tcp_port.601=Syslog-conn
tcp_port.631=IPP
tcp_port.635=RLZ-DBase
tcp_port.636=LDAPS
tcp_port.639=MSDP
tcp_port.641=SupportSoft
tcp_port.643=SANity
tcp_port.646=LDP
tcp_port.647=DHCP-Failover
tcp_port.648=RRP
tcp_port.651=IEEE-MMS
tcp_port.653=SupportSoft-Data
tcp_port.654=MMS
tcp_port.655=Tinc
tcp_port.657=IBM-RMC
tcp_port.660=Mac-Admin
tcp_port.666=Doom
tcp_port.674=ACAP
tcp_port.688=REALM-RUSD
tcp_port.690=VATP
tcp_port.691=MS-Exchange
tcp_port.694=Linux-HA
tcp_port.695=IEEE-MMS-SSL
tcp_port.698=OLSR
tcp_port.700=EPP
tcp_port.701=LMP
tcp_port.702=IRIS-BEEP
tcp_port.706=SILC
